In [1]:
import numpy as np

EJERCICIO 1

In [30]:
#a. A + O = A − O = A
A = np.array([[1,4],[-1,3],[2,-9]])
cero = np.zeros((3,2))
r = A + cero
r2 = A - cero
print("Resultado de A + O:")
print(r)
print("----------------")
print("Resultado de A - O:")
print(r2)
print("----------------")
print("Comprobación (A + O = A − O = A):")
print(np.array_equal(r, A) and np.array_equal(r2, A))

#b. A − A = O
print("----------------")
print("Resultado de A - A:")
r3 = A - A
print(r3)

Resultado de A + O:
[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]
----------------
Resultado de A - O:
[[ 1.  4.]
 [-1.  3.]
 [ 2. -9.]]
----------------
Comprobación (A + O = A − O = A):
True
----------------
Resultado de A - A:
[[0 0]
 [0 0]
 [0 0]]


EJERCICIO 2

In [47]:
print("------------")
print("A+3B")
A = np.array([[3, 0], [-1, 5]])
B = np.array([[4, -2, 1], [0, 2, 3]])
#r = A + 3 * B 
print(" (A + 3 * B ) no es posible realizar la suma de diferentes dimensiones")
print("------------")
print("A*B")
r = A@B
print(r)
print("------------")
print("A³")
r = np.linalg.matrix_power(A, 3)
print("Resultado de A^3:")
print(r)
print("------------")
print("B²")
#r = np.linalg.matrix_power(B, 2)
print("Resultado de B^2:")
print("no es posible elevar a la matriz de diferentes dimensiones (2X3)")
print("------------")
print("(5A)B")
r = (5*A)@B
print("Resultado de (5A)B:")
print(r)



------------
A+3B
 (A + 3 * B ) no es posible realizar la suma de diferentes dimensiones
------------
A*B
[[12 -6  3]
 [-4 12 14]]
------------
A³
Resultado de A^3:
[[ 27   0]
 [-49 125]]
------------
B²
Resultado de B^2:
no es posible elevar a la matriz de diferentes dimensiones (2X3)
------------
(5A)B
Resultado de (5A)B:
[[ 60 -30  15]
 [-20  60  70]]


EJERCICIO 3

In [51]:
restaurantes = np.array([[30,15,4],[25,18,8]])
print(restaurantes)
tiendas = np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print(tiendas.T)
costoPorTienda=restaurantes@tiendas.T
print(costoPorTienda)
print("Tienda 1", (costoPorTienda[0,0]+costoPorTienda[1,0]))
print("Tienda 2", (costoPorTienda[0,1]+costoPorTienda[1,1]))

[[30 15  4]
 [25 18  8]]
[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
[[ 87.   88.9]
 [105.6 107.1]]
Tienda 1 192.6
Tienda 2 196.0


EJERCICIO 4

In [76]:
productos = np.array([[200,75],[150,100],[100,125]])
print(productos.T)
costos = np.array([[1.5,1,2],[1.75,1.50,1]])
print(costos.T)
Rcostos = productos.T@costos.T
print(Rcostos)
print("Por camión", (Rcostos[0,0]+Rcostos[1,0]))
print("Por Tren", (Rcostos[0,1]+Rcostos[1,1]))
print("¡MEJOR OPCION POR TREN!",Rcostos[0,1]+Rcostos[1,1])

[[200 150 100]
 [ 75 100 125]]
[[1.5  1.75]
 [1.   1.5 ]
 [2.   1.  ]]
[[650.   675.  ]
 [462.5  406.25]]
Por camión 1112.5
Por Tren 1081.25
¡MEJOR OPCION POR TREN! 1081.25


EJERCICIO 5

In [86]:
print('''
3x + 2y = 6
6x + 4y = -9
     ↓
''')
A = np.array([[3, 2], [6, 4]])
B = np.array([6, -9])
# Resolver el sistema 
#sol = np.linalg.solve(A, B)
print("Es indetrminada")

print("""
x + y = 3
x − 4y = 1
     ↓
""")
A = np.array([[1, 1], [1, -4]])
B = np.array([3, 1])
# Resolver 
sol = np.linalg.solve(A, B)
print("Solución:")
print("x =", sol[0])
print("y =", sol[1])

print("""
2x − y + 2z = 3
2x + 3y − z = 0
x + 2y + 2z = −12
     ↓
""")
A = np.array([[2, -1, 2], [2, 3, -1], [1, 2, 2]])
B = np.array([3, 0, -12])
# Resolver
sol = np.linalg.solve(A, B)
print("Solución:")
print("x =", sol[0])
print("y =", sol[1])
print("z =", sol[2])




3x + 2y = 6
6x + 4y = -9
     ↓

Es indetrminada

x + y = 3
x − 4y = 1
     ↓

Solución:
x = 2.6
y = 0.4

2x − y + 2z = 3
2x + 3y − z = 0
x + 2y + 2z = −12
     ↓

Solución:
x = 3.6521739130434785
y = -3.782608695652174
z = -4.043478260869565
